# 以Scikit-learn SVM進行鳶尾花(Iris)品種的辨識

## 載入相關套件

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

## 載入資料集

In [2]:
X, y = datasets.load_iris(return_X_y=True)

## 資料分割

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 特徵縮放

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

## 模型訓練

In [5]:
from sklearn.svm import SVC

clf = SVC(probability=True)
clf.fit(X_train_std, y_train)

SVC(probability=True)

## 模型評分

In [6]:
# 計算準確率
y_pred = clf.predict(X_test_std)
print(f"{accuracy_score(y_test, y_pred)*100:.2f}%")

96.67%


In [7]:
clf.support_vectors_

array([[-1.4981074 ,  1.21925117, -1.56616897, -1.31205231],
       [-0.5237286 ,  0.76557631, -1.16859208, -1.31205231],
       [-1.2545127 , -0.14177339, -1.33898217, -1.18257346],
       [-0.88912065,  0.53873889, -1.16859208, -0.92361577],
       [-1.61990474, -1.72963537, -1.39577887, -1.18257346],
       [-0.15833655,  3.03395057, -1.28218547, -1.05309462],
       [-1.86349944, -0.14177339, -1.50937227, -1.44153115],
       [-1.74170209, -0.36861082, -1.33898217, -1.31205231],
       [-0.40193125, -1.72963537,  0.13773199,  0.112215  ],
       [ 1.05963694, -0.14177339,  0.70569898,  0.63013039],
       [-1.010918  , -2.41014765, -0.1462515 , -0.27622154],
       [-0.2801339 , -0.14177339,  0.42171549,  0.37117269],
       [-0.5237286 , -0.14177339,  0.42171549,  0.37117269],
       [ 1.05963694,  0.08506403,  0.53530889,  0.37117269],
       [-0.40193125, -1.27596052,  0.13773199,  0.112215  ],
       [ 0.57244754,  0.53873889,  0.53530889,  0.50065154],
       [ 0.57244754, -1.

In [8]:
clf.support_

array([  0,  54,  58,  71,  93,  98, 107, 118,   4,   7,   8,   9,  12,
        27,  51,  53,  60,  65,  66,  67,  76,  77,  79,  83,  86,  87,
        96, 103, 104,   1,   6,  11,  13,  20,  30,  32,  35,  42,  43,
        49,  56,  57,  72,  73,  99, 102, 117], dtype=int32)

In [9]:
clf.predict_proba(X_test)

array([[0.30646473, 0.27033289, 0.42320238],
       [0.30891831, 0.27704083, 0.41404086],
       [0.30972747, 0.27780309, 0.41246945],
       [0.31202838, 0.27992756, 0.40804406],
       [0.29208184, 0.25576995, 0.4521482 ],
       [0.2719938 , 0.23597419, 0.49203201],
       [0.30462925, 0.26861449, 0.42675626],
       [0.26970835, 0.23375419, 0.49653746],
       [0.31193892, 0.27984537, 0.40821571],
       [0.31158776, 0.27951896, 0.40889328],
       [0.29465146, 0.25847924, 0.4468693 ],
       [0.30873927, 0.27688276, 0.41437797],
       [0.31203016, 0.27992926, 0.40804058],
       [0.28319367, 0.24703641, 0.46976992],
       [0.2522319 , 0.21635887, 0.53140923],
       [0.31202555, 0.27992499, 0.40804945],
       [0.28640732, 0.25038018, 0.4632125 ],
       [0.31203304, 0.27993189, 0.40803508],
       [0.31194386, 0.27984896, 0.40820718],
       [0.31117176, 0.27913792, 0.40969033],
       [0.25684867, 0.22110586, 0.52204547],
       [0.31079653, 0.27882692, 0.41037655],
       [0.

In [10]:
clf.predict_log_proba(X_test)

array([[-1.18265259, -1.30810116, -0.85990478],
       [-1.1746784 , -1.2835904 , -0.88179061],
       [-1.17206251, -1.28084274, -0.88559314],
       [-1.16466115, -1.27322442, -0.89638012],
       [-1.23072123, -1.36347686, -0.79374527],
       [-1.301976  , -1.44403285, -0.7092115 ],
       [-1.18865983, -1.31447805, -0.85154224],
       [-1.31041409, -1.45348519, -0.70009635],
       [-1.16494788, -1.27351808, -0.89595954],
       [-1.16607425, -1.27468515, -0.89430109],
       [-1.22196212, -1.35293991, -0.80548911],
       [-1.17525814, -1.2841611 , -0.88097676],
       [-1.16465542, -1.27321836, -0.89638865],
       [-1.26162427, -1.39821956, -0.75551223],
       [-1.37740639, -1.53081679, -0.63222288],
       [-1.16467019, -1.2732336 , -0.8963669 ],
       [-1.2503403 , -1.3847748 , -0.76956936],
       [-1.16464621, -1.27320897, -0.89640213],
       [-1.16493203, -1.27350525, -0.89598045],
       [-1.16741025, -1.27604929, -0.8923537 ],
       [-1.35926821, -1.50911367, -0.650