In [1]:
# load model
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

model_file_name='model.pickle'
with open(model_file_name, 'rb') as f:
    random_forest = pickle.load(f)

#fare_clf= StandardScaler()
fare_file_name='fare.pickle'
with open(fare_file_name, 'rb') as f:
    fare_clf = pickle.load(f)
    

In [4]:
def far_transform(fare1):
    return fare_clf.transform([[fare1]])[0][0]

def convert_age(age1):
    return age1 // 5 * 5

dict1 = { 'Cherbourg': 0, 'Queenstown': 1, 'Southampton': 2}
def convert_embark_town(embark1):
    x = dict1[embark1]
    if x==0:
        return 1,0,0
    elif x==1:
        return 0,1,0
    else:
        return 0,0,1
        


In [5]:
X = []
# pclass	sex	age	sibsp	parch	fare	embark_town
X.append([3, 0, convert_age(22), 1, 0, far_transform(7.25), dict1['Southampton']]) #*convert_embark_town('Southampton')])
X.append([1, 1, convert_age(35), 1, 0, far_transform(71.2833), dict1['Cherbourg']]) #, *convert_embark_town('Cherbourg')])
X=np.array(X)
X


array([[ 3.        ,  0.        , 20.        ,  1.        ,  0.        ,
        -0.50244517,  2.        ],
       [ 1.        ,  1.        , 35.        ,  1.        ,  0.        ,
         0.78684529,  0.        ]])

In [6]:
random_forest.predict_proba(X)

/home/chesterxalan/github/Classwork/Classwork-PythonMLApplicationDevelopment/.venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[0.66, 0.34],
       [0.01, 0.99]])

In [7]:
random_forest.predict(X)

/home/chesterxalan/github/Classwork/Classwork-PythonMLApplicationDevelopment/.venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 1])